apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart-example
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: "helmvalues:./images-values.yaml"
    argocd-image-updater.argoproj.io/image-list: image=ghcr.io/alexisfr/gitops-cert-level-2-examples
    argocd-image-updater.argoproj.io/image.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/image.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/example.update-strategy: newest-build
spec:
  project: default

  source:
    repoURL: https://github.com/alexisfr/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./image-updater/chart/simple-go-app

  destination:
    server: https://kubernetes.default.svc
    namespace: chart-example

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
